### ISSUE TITLE
`repeat(X; outer, inner)` triggers scalar indexing error with CUDA

### ISSUE THREAD

**Issue by vpuri3** [FluxML/Zygote.jl#1459] opened 2023-10-04 01:47 UTC
https://github.com/FluxML/Zygote.jl/blob/cf7f7d08705d2787fa31bcf45bcca5447fd9a9a7/src/lib/array.jl#L127-L141

**Comment by ToucheSir** [comment] 2023-10-04 02:50
Duplicate of https://github.com/FluxML/Zygote.jl/issues/1442

**Closed** 2023-10-04 02:50 UTC
