### ISSUE TITLE
Insane precompile times in Metalhead models

### ISSUE THREAD

**Issue by theabhirath** [FluxML/Zygote.jl#1160] opened 2022-02-10 11:50 UTC
Xref https://github.com/FluxML/Metalhead.jl/pull/105#discussion_r803526481. When running gradient tests on some [Metalhead](https://github.com/FluxML/Metalhead.jl) models, the times taken for the first gradient are off the charts. Specifically, the function `gradtest` was run on the models in Metalhead#master:

```julia
function gradtest(model, input)
  y, pb = Zygote.pullback(() -> model(input), Flux.params(model))
  gs = pb(ones(Float32, size(y)))

  # if we make it to here with no error, success!
  return true
end
```
and the times taken for the tests were:
![image](https://user-images.githubusercontent.com/74202102/153400693-9d6597f7-7724-48f5-9eb2-e7f3d4c3c4a6.png)

The ViT model can be ignored because `gradtest` wasn't run on it, but it seems to be taking quite a large amount of time for precompilation of the other models...

cc @CarloLucibello

**Comment by DhairyaLGandhi** [comment] 2022-02-10 11:55
Definitely a regression from v0.4, and v0.5.

Honestly surprised no one has complained about it yet. I've been running into this often too. Thanks for the summary!

**Comment by CarloLucibello** [comment] 2022-02-10 12:33
Let's close this since it is a duplicate of #1126, sorry I didn't notice earlier

**Closed by CarloLucibello** 2022-02-10 12:33 UTC
