### ISSUE TITLE
vcat with literal fails

### ISSUE THREAD

**Issue by baggepinnen** [FluxML/Zygote.jl#440] opened 2020-01-02 04:15 UTC
```julia
f = x->[1;x]
Zygote.gradient(sum∘f, randn(3))
```
```
MethodError: no method matching iterate(::Val{1})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...
in(::Int64, ::Val{1}) at operators.jl:1055
(::Zygote.var"#1072#1077"{Int64,Val{1}})(::Int64) at array.jl:98
ntuple(::Zygote.var"#1072#1077"{Int64,Val{1}}, ::Int64) at ntuple.jl:18
(::Zygote.var"#1071#1076"{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},Val{1}})(::Int64) at array.jl:98
map(::Zygote.var"#1071#1076"{FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}},Val{1}}, ::Tuple{Int64,Array{Float64,1}}) at tuple.jl:140
(::Zygote.var"#1069#1074"{Val{1},Tuple{Int64,Array{Float64,1}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at array.jl:97
(::Zygote.var"#2832#back#1080"{Zygote.var"#1069#1074"{Val{1},Tuple{Int64,Array{Float64,1}}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at adjoint.jl:55
(::Zygote.var"#153#154"{Zygote.var"#2832#back#1080"{Zygote.var"#1069#1074"{Val{1},Tuple{Int64,Array{Float64,1}}}},Tuple{Tuple{Nothing,Nothing},Tuple{Nothing,Nothing}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at lib.jl:142
(::Zygote.var"#283#back#155"{Zygote.var"#153#154"{Zygote.var"#2832#back#1080"{Zygote.var"#1069#1074"{Val{1},Tuple{Int64,Array{Float64,1}}}},Tuple{Tuple{Nothing,Nothing},Tuple{Nothing,Nothing}}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at adjoint.jl:49
vcat at abstractarray.jl:1503 [inlined]
(::typeof(∂(vcat)))(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at interface2.jl:0
#23 at runtests.jl:75 [inlined]
(::typeof(∂(#23)))(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at interface2.jl:0
(::Zygote.var"#153#154"{typeof(∂(#23)),Tuple{Tuple{Nothing}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at lib.jl:142
(::Zygote.var"#283#back#155"{Zygote.var"#153#154"{typeof(∂(#23)),Tuple{Tuple{Nothing}}}})(::FillArrays.Fill{Float64,1,Tuple{Base.OneTo{Int64}}}) at adjoint.jl:49
#56 at operators.jl:873 [inlined]
(::typeof(∂(#56)))(::Float64) at interface2.jl:0
(::Zygote.var"#28#29"{typeof(∂(#56))})(::Float64) at interface.jl:38
gradient(::Function, ::Array{Float64,1}) at interface.jl:47
top-level scope at runtests.jl:76
```

**Comment by mcabbott** [comment] 2020-01-08 15:38
The gradients for vcat [here](https://github.com/FluxML/Zygote.jl/blob/0e25138a3c3c88600de2a4ae2999f5a5d4676f02/src/lib/array.jl#L80-84) don't include mixtures of numbers & vectors:
```
@adjoint vcat(A::Union{AbstractVector, AbstractMatrix}...)
@adjoint vcat(xs::Number...)
```

**Comment by merckxiaan** [comment] 2020-02-04 10:04
I'm also running into this problem. Is there a fix somewhere?

**Comment by mcabbott** [comment] 2020-02-04 13:21
```julia
using Zygote

Zygote.@adjoint function vcat(xs::Union{Number, AbstractVector}...)
    vcat(xs...), dy -> begin
        d = 0
        map(xs) do x
            x isa Number && return dy[d+=1]
            l = length(x)
            dx = dy[d+1:d+l]
            d += l
            return dx
        end
    end
end

gradient(x -> sum(vcat(x, 1, x)), rand(3)) == ([2,2,2],)
gradient((x,y) -> sum(vcat(x, y, y)), rand(3), 4) == ([1,1,1], 2)
```

**Comment by merckxiaan** [comment] 2020-02-04 13:58
Thank you!
It seems like I hadn't been running into this exact issue, I've tried to reduce my code to a MWE but was unsuccesful. Here's the stacktrace I'm getting, I'm not sure whether it belongs here or whether I should open a new issue.
```julia
MethodError: no method matching iterate(::Val{1})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...

Stacktrace:
 [1] in(::Int64, ::Val{1}) at .\operators.jl:1055
 [2] (::Zygote.var"#1091#1096"{Array{Float64,3},Val{1}})(::Int64) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\lib\array.jl:103
 [3] ntuple(::Zygote.var"#1091#1096"{Array{Float64,3},Val{1}}, ::Int64) at .\ntuple.jl:18
 [4] (::Zygote.var"#1090#1095"{Array{Float64,3},Val{1}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\lib\array.jl:103
 [5] map at .\tuple.jl:142 [inlined]
 [6] (::Zygote.var"#1088#1093"{Val{1},NTuple{8,Array{Float64,3}}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\lib\array.jl:102
 [7] (::Zygote.var"#2893#back#1099"{Zygote.var"#1088#1093"{Val{1},NTuple{8,Array{Float64,3}}}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:55
 [8] (::Zygote.var"#165#166"{Zygote.var"#2893#back#1099"{Zygote.var"#1088#1093"{Val{1},NTuple{8,Array{Float64,3}}}},Tuple{Tuple{Nothing,Nothing},NTuple{8,Nothing}}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\lib\lib.jl:156
 [9] (::Zygote.var"#321#back#167"{Zygote.var"#165#166"{Zygote.var"#2893#back#1099"{Zygote.var"#1088#1093"{Val{1},NTuple{8,Array{Float64,3}}}},Tuple{Tuple{Nothing,Nothing},NTuple{8,Nothing}}}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:49
 [10] vcat at .\abstractarray.jl:1572 [inlined]
 [11] (::typeof(∂(vcat)))(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface2.jl:0
 [12] (::Zygote.var"#165#166"{typeof(∂(vcat)),Tuple{Int64}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\lib\lib.jl:156
 [13] (::Zygote.var"#321#back#167"{Zygote.var"#165#166"{typeof(∂(vcat)),Tuple{Int64}}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:49
 [14] Multihead_attention at .\In[12]:9 [inlined]
 [15] (::typeof(∂(λ)))(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface2.jl:0
 [16] Encoder at .\In[14]:15 [inlined]
 [17] (::typeof(∂(λ)))(::FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface2.jl:0
 [18] #100 at .\In[22]:2 [inlined]
 [19] (::typeof(∂(#100)))(::Float64) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface2.jl:0
 [20] (::Zygote.var"#46#47"{Params,Zygote.Context,typeof(∂(#100))})(::Float64) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface.jl:101
 [21] gradient(::Function, ::Params) at C:\Users\jules\.julia\packages\Zygote\tJj2w\src\compiler\interface.jl:47
 [22] top-level scope at In[22]:1
```
For reference, things go wrong here: `vcat([head(x, mask) for head in a.heads]...)` where `a.heads` consists of 8 Dense-like layers.

**Comment by mcabbott** [comment] 2020-02-04 14:35
Might be caused by the splat, and fixed by #489? Otherwise you can try https://github.com/mcabbott/LazyStack.jl instead of vcat, like `stack([... for head in a])` perhaps?

**Comment by merckxiaan** [comment] 2020-02-04 15:11
Thanks again, #489 doesn't seem to help so LazyStack seems like the best option. Is there a way to stack along a certain dimension? or should I just reshape the result?

**Comment by mcabbott** [comment] 2020-02-04 15:29
There is not, you would have to reshape. BTW if it doesn't work on CuArrays please make an issue, I may have a fix...

**Comment by merckxiaan** [comment] 2020-02-08 16:51
Ok, I've finally been able to make a MWE for my problem, things seem to go wrong for me when `vcat`ing 3d-arrays:
```julia
using Zygote
Zygote.gradient(x->sum(vcat(x, x)), rand(1,10,10))
```
```julia
MethodError: no method matching iterate(::Val{1})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...

Stacktrace:
 [1] in(::Int64, ::Val{1}) at .\operators.jl:1055
 [2] (::Zygote.var"#1105#1110"{Array{Float64,3},Val{1}})(::Int64) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\lib\array.jl:111
 [3] ntuple(::Zygote.var"#1105#1110"{Array{Float64,3},Val{1}}, ::Int64) at .\ntuple.jl:18
 [4] (::Zygote.var"#1104#1109"{FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}},Val{1}})(::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\lib\array.jl:111
 [5] map(::Zygote.var"#1104#1109"{FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}},Val{1}}, ::Tuple{Array{Float64,3},Array{Float64,3}}) at .\tuple.jl:140
 [6] (::Zygote.var"#1102#1107"{Val{1},Tuple{Array{Float64,3},Array{Float64,3}}})(::FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\lib\array.jl:110
 [7] (::Zygote.var"#2920#back#1113"{Zygote.var"#1102#1107"{Val{1},Tuple{Array{Float64,3},Array{Float64,3}}}})(::FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\Users\jules\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:55
 [8] vcat at .\abstractarray.jl:1571 [inlined]
 [9] (::typeof(∂(vcat)))(::FillArrays.Fill{Float64,3,Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}}) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\compiler\interface2.jl:0
 [10] #47 at .\In[10]:2 [inlined]
 [11] (::typeof(∂(#47)))(::Float64) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\compiler\interface2.jl:0
 [12] (::Zygote.var"#36#37"{typeof(∂(#47))})(::Float64) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\compiler\interface.jl:38
 [13] gradient(::Function, ::Array{Float64,3}) at C:\Users\jules\.julia\packages\Zygote\aPyWm\src\compiler\interface.jl:47
 [14] top-level scope at In[10]:2
```

**Comment by mcabbott** [comment] 2020-02-08 20:53
Didn't know you could do that, but you can do `cat(x, x; dims=1)`.

**Comment by merckxiaan** [comment] 2020-02-08 21:31
Woow, Thanks so much!

**Comment by dehann** [comment] 2020-02-15 21:08
Great this helped me too, thanks!

**Comment by CarloLucibello** [comment] 2020-03-01 09:05
> ```julia
> using Zygote
> 
> Zygote.@adjoint function vcat(xs::Union{Number, AbstractVector}...)
>     vcat(xs...), dy -> begin
>         d = 0
>         map(xs) do x
>             x isa Number && return dy[d+=1]
>             l = length(x)
>             dx = dy[d+1:d+l]
>             d += l
>             return dx
>         end
>     end
> end
> 
> gradient(x -> sum(vcat(x, 1, x)), rand(3)) == ([2,2,2],)
> gradient((x,y) -> sum(vcat(x, y, y)), rand(3), 4) == ([1,1,1], 2)
> ```

@mcabbott is this a valid fix?

**Comment by mcabbott** [comment] 2020-03-01 17:06
Yes I think it's correct, although perhaps a few more torture tests wouldn't hurt. It's fairly different in style to the existing `vcat` gradients, but perhaps that's OK.

**Comment by CarloLucibello** [comment] 2020-03-04 19:08
@mcabbott do you mind submitting a PR? It's a pity if that gets lost

**Closed** 2020-03-11 11:57 UTC
Labels: needs adjoint
