### ISSUE TITLE
Mismatch gradient output with compared to the docs.

### ISSUE THREAD

**Issue by arcAman07** [FluxML/Zygote.jl#1193] opened 2022-04-02 12:27 UTC
Going through the docs of the current release of Zygote.jl for this example:

`julia> gradient(colordiff, RGB(1, 0, 0), RGB(0, 1, 0))
((r = 0.4590887719632896, g = -9.598786801605689, b = 14.181383399012862), (r = -1.7697549557037275, g = 28.88472330558805, b = -0.044793892637761346))`

I am getting the output as:

(nothing, nothing)

**Comment by darsnack** [comment] 2022-04-02 13:57
Closing as a duplicate of #1186. If you can help bisect which version the error surfaced at, please comment in that thread.

**Closed** 2022-04-02 13:57 UTC
