### ISSUE TITLE
ERROR: LoadError: UndefVarError: splatnew not defined

### ISSUE THREAD

**Issue by freddycct** [FluxML/Zygote.jl#456] opened 2020-01-13 17:39 UTC
```
ERROR: LoadError: UndefVarError: splatnew not defined
Stacktrace:
 [1] NamedTuple at ./boot.jl:553 [inlined]
 [2] NamedTuple at ./boot.jl:549 [inlined]
 [3] macro expansion at /home/fchua/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:186 [inlined]
 [4] pair at /home/fchua/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:186 [inlined]
 [5] back at /home/fchua/.julia/packages/Zygote/oPQFy/src/lib/lib.jl:193 [inlined]
```

**Comment by MikeInnes** [comment] 2020-01-13 18:10
What Julia version are you on? If it's pre-1.0 I don't think we support that any more.

**Comment by freddycct** [comment] 2020-01-13 18:11
1.3.1

The training runs fine for a while until this happened.

**Comment by CarloLucibello** [comment] 2020-02-27 10:02
@freddycct Is this by just `using Zygote`? Could you post some additional info?

**Comment by freddycct** [comment] 2020-02-27 18:04
I did have the `using Zygote` line in the code, I also have the `using Flux` line.

I did that so that I can write this code
```
function gradientWithLoss(f, args...)
  y, back = Flux.pullback(f, args...)
  return y, back(Zygote.sensitivity(y))
end
```
the code above is a slight modification of the following, see https://github.com/FluxML/Zygote.jl/blob/master/src/compiler/interface.jl
line 45-48
```
function gradient(f, args...)
  y, back = pullback(f, args...)
  return back(sensitivity(y))
end
```

**Comment by freddycct** [comment] 2020-03-04 18:26
So far, I haven't experience this problem after updating to the latest Zygote and Flux versions. Hopefully it continues this way.

**Comment by freddycct** [comment] 2020-03-06 09:16
Issue still exists despite being Zygote v0.4.9 and Flux v0.10.3

**Comment by freddycct** [comment] 2020-03-08 22:45
```
ERROR: LoadError: UndefVarError: splatnew not defined
Stacktrace:
 [1] NamedTuple at ./boot.jl:553 [inlined]
 [2] NamedTuple at ./boot.jl:549 [inlined]
 [3] macro expansion at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:189 [inlined]
 [4] pair at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:189 [inlined]
 [5] back at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:196 [inlined]
 [6] at /data/home/fchua/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
```

**Comment by freddycct** [comment] 2020-03-09 16:22
Did some changes to my code, and got this
```
ERROR: LoadError: TypeError: in new, expected Pair{Symbol,Bool}, got NamedTuple

Stacktrace:
 [1] NamedTuple at ./boot.jl:553 [inlined]
 [2] NamedTuple at ./boot.jl:549 [inlined]
 [3] macro expansion at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:189 [inlined]
 [4] pair at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:189 [inlined]
 [5] back at /data/home/fchua/.julia/packages/Zygote/ApBXe/src/lib/lib.jl:196 [inlined]
 [6] ... /data/home/fchua/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
```

**Comment by freddycct** [comment] 2020-04-24 18:52
I think my issue in here is related to #399, #489 and #599. This error occured while doing gradient update based on a tuple of return values.

**Comment by CarloLucibello** [comment] 2020-04-26 08:29
closing this, since it could be a dup and also no code for reproducing the error is given

**Closed by CarloLucibello** 2020-04-26 08:29 UTC

**Comment by freddycct** [comment] 2020-04-26 16:06
I did try to provide MWE, it happens randomly in my big software system, but not in the MWE

**Comment by freddycct** [comment] 2020-04-27 04:42
I finally found a way to avoid this problem, 

I had to use Dict{Symbol, Any} to define the variables in my struct instead

struct A
   a::Int
end

this will randomly lead to crash but i have to do this

struct A
  params::Dict{Symbol, Int}
  A(x) = new(Dict{Symbol,Int}((:a => x))
end
