### ISSUE TITLE
`vcat(::Vector, ::Pair)` gradient bug

### ISSUE THREAD

**Issue by mtfishman** [FluxML/Zygote.jl#1223] opened 2022-05-10 20:47 UTC
Here is a minimal example of a bug we've come across when differentiating `vcat`:
```julia
using Zygote

f(x) = last(vcat([], 1 => x)[1])

@show f(3.0), f'(3.0)
```
which throws the error:
```julia
ERROR: LoadError: MethodError: no method matching size(::Pair{Int64, Float64}, ::Int64)
Closest candidates are:
  size(::Union{LinearAlgebra.QR, LinearAlgebra.QRCompactWY, LinearAlgebra.QRPivoted}, ::Integer) at ~/software/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/qr.jl:566
  size(::Union{LinearAlgebra.Cholesky, LinearAlgebra.CholeskyPivoted}, ::Integer) at ~/software/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/cholesky.jl:495
  size(::Union{LinearAlgebra.Hermitian{T, S}, LinearAlgebra.Symmetric{T, S}} where {T, S}, ::Any) at ~/software/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:201
  ...
Stacktrace:
  [1] #519
    @ ~/.julia/packages/Zygote/ytjqm/src/lib/array.jl:124 [inlined]
  [2] ntuple
    @ ./ntuple.jl:19 [inlined]
  [3] (::Zygote.var"#518#523"{Vector{NamedTuple{(:first, :second), Tuple{Nothing, Float64}}}, Tuple{Bool}})(x::Pair{Int64, Float64})
    @ Zygote ~/.julia/packages/Zygote/ytjqm/src/lib/array.jl:124
  [4] map
    @ ./tuple.jl:222 [inlined]
  [5] #516
    @ ~/.julia/packages/Zygote/ytjqm/src/lib/array.jl:123 [inlined]
  [6] #2534#back
    @ ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:73 [inlined]
  [7] #212
    @ ~/.julia/packages/Zygote/ytjqm/src/lib/lib.jl:203 [inlined]
  [8] #1750#back
    @ ~/.julia/packages/ZygoteRules/AIbCs/src/adjoint.jl:67 [inlined]
  [9] Pullback
    @ ./abstractarray.jl:1772 [inlined]
 [10] (::typeof(∂(vcat)))(Δ::Vector{NamedTuple{(:first, :second), Tuple{Nothing, Float64}}})
    @ Zygote ~/.julia/packages/Zygote/ytjqm/src/compiler/interface2.jl:0
 [11] Pullback
    @ [...]/minimal.jl:3 [inlined]
 [12] (::typeof(∂(f)))(Δ::Float64)
    @ Zygote ~/.julia/packages/Zygote/ytjqm/src/compiler/interface2.jl:0
 [13] (::Zygote.var"#56#57"{typeof(∂(f))})(Δ::Float64)
    @ Zygote ~/.julia/packages/Zygote/ytjqm/src/compiler/interface.jl:41
 [14] (::Zygote.var"#58#59"{typeof(f)})(x::Float64)
    @ Zygote ~/.julia/packages/Zygote/ytjqm/src/compiler/interface.jl:83
 [15] top-level scope
    @ show.jl:1047
 [16] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [17] top-level scope
    @ REPL[15]:1
in expression starting at [...]/minimal.jl:5
```

These variations work as expected:
```julia
using Zygote

f(x) = last(vcat([], x)[1])

@show f(3.0), f'(3.0)
```
and
```julia
f(x) = last(vcat([], [1 => x])[1])

@show f(3.0), f'(3.0)
```
which both output:
```julia
(f(3.0), (f')(3.0)) = (3.0, 1.0)
```

Version information:
```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vim

julia> using Pkg; Pkg.status("Zygote")
      Status `[...]/Project.toml`
  [e88e6eb3] Zygote v0.6.40
```

**Comment by ToucheSir** [comment] 2022-05-10 20:53
Looks like a dupe of https://github.com/FluxML/Zygote.jl/issues/1201?

**Comment by mtfishman** [comment] 2022-05-10 21:11
Could be, thanks for pointing out that issue. Looks like the error message here is a bit different, but maybe has the same root cause that the adjoint/rrule definition is too specialized.

**Comment by ToucheSir** [comment] 2022-05-10 21:25
That's because the function being called is difference (`hvcat` vs `vcat`), but based on your description the underlying issue is the same. The solution is also similar: add a path in ChainRules to handle non-numeric types.

I've updated that issue title to also encompass `vcat`, so closing this to have a one less loose end to follow :)

**Closed by ToucheSir** 2022-05-10 21:25 UTC
