### ISSUE TITLE
gradient on Distances.jl evaluate causes Julia to crash

### ISSUE THREAD

**Issue by theogf** [FluxML/Zygote.jl#429] opened 2019-12-17 13:23 UTC
Here is a MWE : 
```julia
using Distances, Zygote
X = rand(10,10)
Zygote.gradient(x->evaluate(SqEuclidean(),x*X[:,1],x*X[:,1]),3.0)
```
It does only fail but also crash Julia
Here is the beginning of the error messages :
```
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Any, (87,)}[
  Core.Compiler.VarState(typ=Zygote.Pullback{Tuple{typeof(Distances._evaluate), Distances.SqEuclidean, Array{Float64, 1}, Array{Float64, 1}}, Any}, undef=false),
```

**Comment by baggepinnen** [comment] 2019-12-17 22:44
Duplicate of https://github.com/FluxML/Zygote.jl/issues/385

**Closed** 2020-02-27 09:28 UTC
